### ISSUE TITLE
Offset feature

### ISSUE THREAD

**Issue by electerious** [electerious/basicScroll#17]
See https://github.com/electerious/basicScroll/pull/15

**Comment by adeoh** [comment]
Also could work to add points in between the actual relative position values

**Comment by sjelfull** [comment]
Any idea on how to hack this in?

**Comment by pngarland** [comment]
@sjelfull this worked for me: https://github.com/electerious/basicScroll/pull/15/commits/8dbca50aab98e3ee0017927a839cf62cd19051ae

**Comment by electerious** [comment]
### Recommended solution

A custom anchor can be used to adjust `from` and `to` of an element.

![anchor](https://user-images.githubusercontent.com/499088/50310579-b76b8200-04a2-11e9-892c-e309916c9fc7.png)

*Anchor = Orange; Elem = Gray*

``` css
.elem {
	position: relative;
}

.anchor {
	position: absolute;
	top: -100px;
	left: 0;
	right: 0;
	bottom: -100px;
	pointer-events: none;

	/* For debugging */
	right: 50%;
	background: orange;
	opacity: .5;
}
```

```html
<div class="elem">
	<div class="anchor"></div>
</div>
```

```js
basicScroll.create({
	elem: document.querySelector('.anchor'),
	from: 'top-bottom',
	to: 'bottom-top',
	direct: document.querySelector('.elem'),
	props: {
		'--opacity': {
			from: .01,
			to: .99
		}
	}
})
```

This will change `--opacity` from `0.01` to `0.99`. It starts when the top of the anchor is at the bottom of the viewport and ends when the bottom of the anchor is at the top of the viewport. The anchor starts `100px` in front of the element and `100px` after the element thanks to the size specified in the CSS.

See [direct mode](https://github.com/electerious/basicScroll#direct-mode) for more details.
